# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.define "xrv", primary: true do |xrv|
    xrv.vm.box = "IOS XRv"
    xrv.vm.network :private_network, virtualbox__intnet: "connection", auto_config: false
    xrv.vm.network "forwarded_port", guest: 57780, host: 57780
    xrv.vm.network "forwarded_port", guest: 58822, host: 58822
    xrv.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end

    xrv.vm.provision "file", source: "xrv/demo.xml", destination: "/home/vagrant/demo.xml"
    xrv.vm.provision "file", source: "xrv/router_config", destination: "/home/vagrant/router_config"
    if File.exist? File.expand_path "solenoid.tgz"
        xrv.vm.provision "file", source: "solenoid.tgz", destination: "/home/vagrant/solenoid.tgz"
    else
        xrv.vm.provision :shell, inline: "curl -L 'https://cisco.box.com/shared/static/9no4xqjtm8q05ofmsa5dhe52hv3tmof7.tgz' -o 'solenoid.tgz'"
    end
    xrv.vm.provision :shell, path: "xrv/bootstrap.sh"
  end

   config.vm.define "devbox", primary: true do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.network :private_network, virtualbox__intnet: "connection", ip: "11.1.1.20"
    ubuntu.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
    ubuntu.vm.provision :shell, path: "devbox/bootstrap_ubuntu.sh"
  end
end
